version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: betting_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app  # Mount the local backend directory to the container
      - /usr/src/app/node_modules  # Ensure node_modules are used from within the container
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - NODE_ENV=development
    depends_on:
      - postgres

volumes:
  postgres_data:
